[package]
name = "emailmaker"
version = "0.1.0"
edition = "2021"

[dependencies]
calamine = "0.26.1"
clap = { version = "4.4", features = ["derive"] }
percent-encoding = "2.3"
regex = "1.10"
open = "5.0"
rfd = "0.15.2"
